### ISSUE TITLE
Unable to find a specification

### ISSUE THREAD

**Issue by JohnGeorge** [davnag/DJSemiModalViewController#1]
[!] Unable to find a specification for 'DJSemiModalViewController' when trying to install pod.

**Comment by astrokin** [comment]
try to use this in your podfile 
`pod 'DJSemiModalViewController', :git => 'https://github.com/davnag/DJSemiModalViewController'`

**Comment by davnag** [comment]
@astrokin Do you know how I can register it properly?

**Comment by astrokin** [comment]
@davnag you need to push you spec to the trunk (master) of CocoaPods repo
run in terminal
1. pod spec lint DJSemiModalViewController.podspec (to make sure that everything is OK)
2. pod trunk push DJSemiModalViewController.podspec (to make it public)
good luck!

for more details you can visit https://guides.cocoapods.org/making/getting-setup-with-trunk.html

**Comment by davnag** [comment]
@JohnGeorge This is finally fixed with version 0.1.3 update.
@astrokin Thank you for your support!
