### ISSUE TITLE
Dismiss after timeout

### ISSUE THREAD

**Issue by anees17861** [davnag/DJSemiModalViewController#2]
Is there a way to dismiss the alert view programmatically? Currently it seems like you can only do it by close button.

I'm trying to automatically dismiss it after 2 seconds.
I tried calling dismiss(animated: true) which is actually a function of UIViewController but this just removes the dialog and keeps the background view dark and unusable

The function dismissAction seems to be doing exactly what i require but it's a private func.

**Comment by davnag** [comment]
@anees17861 Update to latest version 0.1.4.

Now you can use the default `dismiss(animated: true)` like for a regular `UIViewController`.

```swift 
DispatchQueue.main.asyncAfter(deadline: .now() + .milliseconds(1000)) {
   [DJSemiModalViewController].dismiss(animated: true)
}
```

I hope this will help you!
